### ISSUE TITLE
Input information for the key generation circuits

### ISSUE THREAD

**Issue by joerowell** [n-for-1-auth/circuits#4]
Is there any information available about the input layout expected for the key generation circuits? 

To give an example of what I mean, the ```AES-non-expanded``` circuit expects the input in this format:

```<message bits><key bits>```

This can be seen e.g [here](https://github.com/emp-toolkit/emp-ag2pc/blob/c40d5e5b1087fa5c289a98450e3ece1a643b27fb/test/aes_mult_inputs.cpp#L14):

```
// NIST test vector
string input_message_key = "00112233445566778899AABBCCDDEEFF000102030405060708090A0B0C0D0E0F";
```

Thanks so much! :)

**Comment by weikengchen** [comment]
I hope this script would be helpful: https://github.com/n-for-1-auth/circuits/blob/main/generator/generate_handshake_circuits.cpp

**Comment by joerowell** [comment]
Hey @weikengchen! Sorry, I should have closed this: I figured it out a while back :) Thanks for commenting anyway!
